// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/gin-gonic/gin"
	"github.com/tscolari/thruster"
)

type FakeController struct {
	IndexStub        func(context *gin.Context) (interface{}, error)
	indexMutex       sync.RWMutex
	indexArgsForCall []struct {
		context *gin.Context
	}
	indexReturns struct {
		result1 interface{}
		result2 error
	}
	ShowStub        func(context *gin.Context) (interface{}, error)
	showMutex       sync.RWMutex
	showArgsForCall []struct {
		context *gin.Context
	}
	showReturns struct {
		result1 interface{}
		result2 error
	}
	CreateStub        func(context *gin.Context) (interface{}, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		context *gin.Context
	}
	createReturns struct {
		result1 interface{}
		result2 error
	}
	UpdateStub        func(context *gin.Context) (interface{}, error)
	updateMutex       sync.RWMutex
	updateArgsForCall []struct {
		context *gin.Context
	}
	updateReturns struct {
		result1 interface{}
		result2 error
	}
	DestroyStub        func(context *gin.Context) (interface{}, error)
	destroyMutex       sync.RWMutex
	destroyArgsForCall []struct {
		context *gin.Context
	}
	destroyReturns struct {
		result1 interface{}
		result2 error
	}
}

func (fake *FakeController) Index(context *gin.Context) (interface{}, error) {
	fake.indexMutex.Lock()
	fake.indexArgsForCall = append(fake.indexArgsForCall, struct {
		context *gin.Context
	}{context})
	fake.indexMutex.Unlock()
	if fake.IndexStub != nil {
		return fake.IndexStub(context)
	} else {
		return fake.indexReturns.result1, fake.indexReturns.result2
	}
}

func (fake *FakeController) IndexCallCount() int {
	fake.indexMutex.RLock()
	defer fake.indexMutex.RUnlock()
	return len(fake.indexArgsForCall)
}

func (fake *FakeController) IndexArgsForCall(i int) *gin.Context {
	fake.indexMutex.RLock()
	defer fake.indexMutex.RUnlock()
	return fake.indexArgsForCall[i].context
}

func (fake *FakeController) IndexReturns(result1 interface{}, result2 error) {
	fake.IndexStub = nil
	fake.indexReturns = struct {
		result1 interface{}
		result2 error
	}{result1, result2}
}

func (fake *FakeController) Show(context *gin.Context) (interface{}, error) {
	fake.showMutex.Lock()
	fake.showArgsForCall = append(fake.showArgsForCall, struct {
		context *gin.Context
	}{context})
	fake.showMutex.Unlock()
	if fake.ShowStub != nil {
		return fake.ShowStub(context)
	} else {
		return fake.showReturns.result1, fake.showReturns.result2
	}
}

func (fake *FakeController) ShowCallCount() int {
	fake.showMutex.RLock()
	defer fake.showMutex.RUnlock()
	return len(fake.showArgsForCall)
}

func (fake *FakeController) ShowArgsForCall(i int) *gin.Context {
	fake.showMutex.RLock()
	defer fake.showMutex.RUnlock()
	return fake.showArgsForCall[i].context
}

func (fake *FakeController) ShowReturns(result1 interface{}, result2 error) {
	fake.ShowStub = nil
	fake.showReturns = struct {
		result1 interface{}
		result2 error
	}{result1, result2}
}

func (fake *FakeController) Create(context *gin.Context) (interface{}, error) {
	fake.createMutex.Lock()
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		context *gin.Context
	}{context})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(context)
	} else {
		return fake.createReturns.result1, fake.createReturns.result2
	}
}

func (fake *FakeController) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeController) CreateArgsForCall(i int) *gin.Context {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].context
}

func (fake *FakeController) CreateReturns(result1 interface{}, result2 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 interface{}
		result2 error
	}{result1, result2}
}

func (fake *FakeController) Update(context *gin.Context) (interface{}, error) {
	fake.updateMutex.Lock()
	fake.updateArgsForCall = append(fake.updateArgsForCall, struct {
		context *gin.Context
	}{context})
	fake.updateMutex.Unlock()
	if fake.UpdateStub != nil {
		return fake.UpdateStub(context)
	} else {
		return fake.updateReturns.result1, fake.updateReturns.result2
	}
}

func (fake *FakeController) UpdateCallCount() int {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return len(fake.updateArgsForCall)
}

func (fake *FakeController) UpdateArgsForCall(i int) *gin.Context {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return fake.updateArgsForCall[i].context
}

func (fake *FakeController) UpdateReturns(result1 interface{}, result2 error) {
	fake.UpdateStub = nil
	fake.updateReturns = struct {
		result1 interface{}
		result2 error
	}{result1, result2}
}

func (fake *FakeController) Destroy(context *gin.Context) (interface{}, error) {
	fake.destroyMutex.Lock()
	fake.destroyArgsForCall = append(fake.destroyArgsForCall, struct {
		context *gin.Context
	}{context})
	fake.destroyMutex.Unlock()
	if fake.DestroyStub != nil {
		return fake.DestroyStub(context)
	} else {
		return fake.destroyReturns.result1, fake.destroyReturns.result2
	}
}

func (fake *FakeController) DestroyCallCount() int {
	fake.destroyMutex.RLock()
	defer fake.destroyMutex.RUnlock()
	return len(fake.destroyArgsForCall)
}

func (fake *FakeController) DestroyArgsForCall(i int) *gin.Context {
	fake.destroyMutex.RLock()
	defer fake.destroyMutex.RUnlock()
	return fake.destroyArgsForCall[i].context
}

func (fake *FakeController) DestroyReturns(result1 interface{}, result2 error) {
	fake.DestroyStub = nil
	fake.destroyReturns = struct {
		result1 interface{}
		result2 error
	}{result1, result2}
}

var _ thruster.Controller = new(FakeController)
